# Generated by Django 6.0.2 on 2026-02-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, unique=True)),
                (
                    "condition",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        verbose_name="体調",
                    ),
                ),
                (
                    "metal_status",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        verbose_name="精神状態",
                    ),
                ),
                (
                    "wakeup_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="起床時間"
                    ),
                ),
                (
                    "bed_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="就寝時間"
                    ),
                ),
                (
                    "sleep_duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="睡眠時間(h)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_user_daily_record"
                    )
                ],
            },
        ),
    ]
