# Generated by Django 6.0.2 on 2026-02-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="healthrecord",
            old_name="metal_status",
            new_name="mental_status",
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
