# Generated by Django 6.0.2 on 2026-02-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthapp", "0002_rename_metal_status_healthrecord_mental_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="memo",
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
