# Generated by Django 6.0.2 on 2026-02-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthapp", "0003_healthrecord_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="体重",
            ),
        ),
    ]
